### ISSUE TITLE
Can shift-click items into the bookshelf GUI. Which will be purged after closing.

### ISSUE THREAD

**Issue by Uboaaaaa** [Cynadyde/BookshelfDisplay#1]
Server version: 1.16.3, paper #251.
plugin version: 1.14.4

Issue: Although one cannot drag items around a bookshelf GUI, players can put items in by shift-left-clicking them. The items will pop into the bookshelf and cannot be take out. Closing the GUI leads to items being purged forever.

**Comment by Cynadyde** [comment]
should be taken care of in the new build.
Thanks!
